# Generated by Django 2.2.16 on 2023-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='gamemanufacturer',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='games',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
