# Generated by Django 2.2.16 on 2023-12-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20231228_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='image',
            new_name='uri',
        ),
        migrations.RenameField(
            model_name='gamemanufacturer',
            old_name='image',
            new_name='uri',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='image',
            new_name='uri',
        ),
    ]
