# Generated by Django 2.2.16 on 2024-01-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20240104_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gameManufacturer',
            new_name='gameCategory',
        ),
    ]
