# Generated by Django 2.2.16 on 2023-11-13 17:15

import apps.admin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0008_robot_userrobot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantifyOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.admin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.admin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('isDel', models.IntegerField(default=0, null=True, verbose_name='是否删除')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.admin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.admin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('orderNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单单号')),
                ('investmentAmount', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='投资金额')),
                ('income', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='收益')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantifyOrders_robot', to='member.UserRobot', verbose_name='关联用户机器人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantifyOrders_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '量化订单',
                'verbose_name_plural': '量化订单',
            },
        ),
    ]
