# Generated by Django 2.2.16 on 2023-11-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20231114_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserobotorders',
            name='realAmount',
            field=models.IntegerField(null=True, verbose_name='会员价格'),
        ),
        migrations.AddField(
            model_name='purchaseviporders',
            name='realAmount',
            field=models.IntegerField(null=True, verbose_name='会员价格'),
        ),
        migrations.AlterField(
            model_name='payorders',
            name='quantifyOrders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PayOrders_order', to='order.QuantifyOrders', verbose_name='关联交易订单'),
        ),
    ]
