# Generated by Django 2.2.16 on 2023-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20231117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorders',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchaserobotorders',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchaseviporders',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='quantifyorders',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
    ]
