# Generated by Django 2.2.16 on 2023-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_incomerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseviporders',
            name='payUri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='支付截图'),
        ),
    ]
