# Generated by Django 2.2.16 on 2023-12-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_paychannel_qrcode'),
        ('order', '0007_purchaseviporders_payuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseviporders',
            name='payChannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseVipOrders_payChannel', to='pay.PayChannel', verbose_name='关联支付'),
        ),
    ]
