# Generated by Django 2.2.16 on 2024-01-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_purchaseviporders_paychannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserobotorders',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='purchaserobotorders',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='purchaserobotorders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quantifyorders',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quantifyorders',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='quantifyorders',
            name='user',
        ),
        migrations.DeleteModel(
            name='PayOrders',
        ),
        migrations.DeleteModel(
            name='PurchaseRobotOrders',
        ),
        migrations.DeleteModel(
            name='QuantifyOrders',
        ),
    ]
