# Generated by Django 2.2.16 on 2023-11-10 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inviteCode',
            field=models.CharField(max_length=20, null=True, verbose_name='邀请码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentId', to=settings.AUTH_USER_MODEL, verbose_name='上级用户'),
        ),
    ]
