# Generated by Django 2.2.16 on 2023-11-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20231124_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='性别'),
        ),
    ]
