# Generated by Django 2.2.16 on 2023-11-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_auto_20231124_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
    ]
