# Generated by Django 2.2.16 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerylog',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='configsettings',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='dictdata',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='dictdetails',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='logininfor',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='messagepush',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='savefile',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
    ]
