# Generated by Django 2.2.16 on 2023-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_announcement_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='排序'),
        ),
    ]
