# Generated by Django 2.2.16 on 2023-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_banners_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiration',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='isExpiration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否到期'),
        ),
        migrations.AddField(
            model_name='banners',
            name='expiration',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='banners',
            name='isExpiration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否到期'),
        ),
        migrations.AddField(
            model_name='marquee',
            name='expiration',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='marquee',
            name='isExpiration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否到期'),
        ),
    ]
