# Generated by Django 2.2.16 on 2023-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20231115_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片路径'),
        ),
    ]
