# Generated by Django 2.2.16 on 2023-11-21 10:37

import apps.admin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.admin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.admin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('isDel', models.IntegerField(default=0, null=True, verbose_name='是否删除')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.admin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.admin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, help_text='渠道名称', max_length=100, null=True, verbose_name='渠道名称')),
                ('minQuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最大限额')),
                ('maxQuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最小限额')),
                ('payKey', models.CharField(blank=True, help_text='渠道key', max_length=100, null=True, verbose_name='渠道key')),
                ('payCode', models.CharField(blank=True, help_text='支付编号', max_length=100, null=True, verbose_name='支付编号')),
                ('sort', models.IntegerField(blank=True, help_text='排序', null=True, verbose_name='排序')),
                ('status', models.IntegerField(blank=True, default=0, help_text='状态', null=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '会员卡管理',
                'verbose_name_plural': '会员卡管理',
            },
        ),
    ]
