# Generated by Django 2.2.16 on 2023-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychannel',
            name='maxQuota',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最大限额'),
        ),
        migrations.AlterField(
            model_name='paychannel',
            name='minQuota',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最小限额'),
        ),
        migrations.AlterField(
            model_name='paychannel',
            name='status',
            field=models.IntegerField(blank=True, default=1, help_text='状态', null=True, verbose_name='状态'),
        ),
    ]
