# Generated by Django 2.2.16 on 2023-12-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_paychannel_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychannel',
            name='type',
            field=models.IntegerField(blank=True, default=0, help_text='支付类型', null=True, verbose_name='支付类型'),
        ),
    ]
