# Generated by Django 2.2.16 on 2024-01-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lives',
            old_name='hot',
            new_name='heatValue',
        ),
    ]
