# Generated by Django 2.2.16 on 2023-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcard',
            name='discountAmount',
            field=models.IntegerField(null=True, verbose_name='优惠价格'),
        ),
        migrations.AlterField(
            model_name='vipcard',
            name='originAmount',
            field=models.IntegerField(null=True, verbose_name='实际价格'),
        ),
    ]
