# Generated by Django 2.2.16 on 2023-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20231111_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcard',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
    ]
