# Generated by Django 2.2.16 on 2023-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_userexchangeconfig_uservip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservip',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='vipcard',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
    ]
