# Generated by Django 2.2.16 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20231111_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchangeconfig',
            name='isDel',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
    ]
