# Generated by Django 2.2.16 on 2023-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_robot_userrobot'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipcard',
            name='vipCardType',
            field=models.IntegerField(blank=True, null=True, verbose_name='会员卡类型'),
        ),
    ]
