# Generated by Django 2.2.16 on 2023-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_vipcard_vipcardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.IntegerField(default=1, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userrobot',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='vipcard',
            name='status',
            field=models.IntegerField(default=1, null=True, verbose_name='状态'),
        ),
    ]
