# Generated by Django 2.2.16 on 2023-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20231114_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrobot',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
    ]
