# Generated by Django 2.2.16 on 2023-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20231120_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservip',
            name='isExpiration',
        ),
        migrations.AddField(
            model_name='robot',
            name='isRecommend',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='uservip',
            name='isRecommend',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='vipcard',
            name='isDefault',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否默认'),
        ),
    ]
