# Generated by Django 2.2.16 on 2023-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20231124_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservip',
            name='isExpiration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否到期'),
        ),
    ]
